package uniajc.edu.dao;

import uniajc.edu.model.*;
import uniajc.edu.conexion.*;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;

import com.google.gson.Gson;

public class LiquidacionDao {
	


public Liquidacion Liquidacion(int P_ID) {
		
		
		Liquidacion Liqui = new Liquidacion();
		ConnectionDB conn = new ConnectionDB();
		 
		 try {
			 conn.connect();
			String sql=("SELECT LIQU.LIQU_ID,PEGE.PEGE_DOCUMENTOIDENTIDAD AS DOCUMENTO,PENG.PENG_PRIMERAPELLIDO||' '||PENG.PENG_SEGUNDOAPELLIDO||' '||PENG.PENG_PRIMERNOMBRE||' '||PENG.PENG_SEGUNDONOMBRE AS NOMBRE,"
					+"PROG.PROG_CODIGOPROGRAMA AS COD_PROG,PROG.PROG_NOMBRE AS PROGRAMA,FRAN.FRAN_DESCRIPCION AS FRANJA,CATE.CATE_DESCRIPCION AS CATEGORIA,SITE.SITE_DESCRIPCION AS SITUACION,"
					+"ESTP.ESTP_ID,LIQU.LIQU_TOTALLIQUIDADO AS TOTAPAGAR,LIQU.LIQU_TOTALDESCUENTO AS DESCUENTO, LIQU.LIQU_VALORPAGADO AS V_PAGADO,LIQU.LIQU_ESTADO,LIQU.LIQU_TIPOLIQUIDACION AS TIPO_LIQU,"
					+"MAAC.MAAC_ESTADO,LIQU.PEUN_ID,MAAC.PEUN_ID AS PEUN_MATRICULA,ESTP.ESTP_PERIODOACADEMICO AS SEMESTRE"
					+"FROM ACADEMICO.LIQUIDACION LIQU,ACADEMICO.ESTUDIANTEPENSUM ESTP,ACADEMICO.PROGRAMA PROG,ACADEMICO.UNIDADPROGRAMA UNPR,ACADEMICO.PERSONAGENERAL PEGE,"
					+"ACADEMICO.PERSONANATURALGENERAL PENG,ACADEMICO.MATRICULAACADEMICA MAAC,ACADEMICO.CATEGORIA CATE,ACADEMICO.SITUACIONESTUDIANTE SITE,ACADEMICO.FRANJA FRAN"
					+"WHERE ESTP.FRAN_ID=FRAN.FRAN_ID"
					+"AND ESTP.CATE_ID=CATE.CATE_ID"
					+"AND ESTP.SITE_ID=SITE.SITE_ID"
					+"AND MAAC.ESTP_ID(+)=ESTP.ESTP_ID"
					+"AND ESTP.SITE_ID IN(5,11)"
					+"AND ESTP.PEGE_ID=PEGE.PEGE_ID"
					+"AND ESTP.UNPR_ID=UNPR.UNPR_ID"
					+"AND UNPR.PROG_ID=PROG.PROG_ID"
					+"AND LIQU.LIQU_ESTADO='PAGADO'"
					+"AND LIQU.LIQU_TIPOLIQUIDACION='NORMAL'"
					+"AND PROG.TPPA_ID=1"
					+"AND LIQU.ESTP_ID(+)=ESTP.ESTP_ID"
					+"AND LIQU.PEUN_ID=452"
					+"AND MAAC.PEUN_ID(+)=452"
					+"AND LIQU.LIQU_ESTADO NOT IN 'ANULADO' "
					+"AND PENG.PEGE_ID="+P_ID+""
					+"UNION"
					+"SELECT LIQU.LIQU_ID,PEGE.PEGE_DOCUMENTOIDENTIDAD AS DOCUMENTO,PENG.PENG_PRIMERAPELLIDO||' '||PENG.PENG_SEGUNDOAPELLIDO||' '||PENG.PENG_PRIMERNOMBRE||' '||PENG.PENG_SEGUNDONOMBRE AS NOMBRE,"
					+"PROG.PROG_CODIGOPROGRAMA AS COD_PROG,PROG.PROG_NOMBRE AS PROGRAMA,FRAN.FRAN_DESCRIPCION AS FRANJA,CATE.CATE_DESCRIPCION AS CATEGORIA,SITE.SITE_DESCRIPCION AS SITUACION,"
					+"ESTP.ESTP_ID,LIQU.LIQU_TOTALLIQUIDADO AS TOTAPAGAR,LIQU.LIQU_TOTALDESCUENTO AS DESCUENTO, LIQU.LIQU_VALORPAGADO AS V_PAGADO,LIQU.LIQU_ESTADO,LIQU.LIQU_TIPOLIQUIDACION AS TIPO_LIQU,"
					+"MAAC.MAAC_ESTADO,LIQU.PEUN_ID,MAAC.PEUN_ID AS PEUN_MATRICULA,ESTP.ESTP_PERIODOACADEMICO AS SEMESTRE"
					+"FROM ACADEMICO.LIQUIDACION LIQU,ACADEMICO.ESTUDIANTEPENSUM ESTP,ACADEMICO.PROGRAMA PROG,ACADEMICO.UNIDADPROGRAMA UNPR,ACADEMICO.PERSONAGENERAL PEGE,ACADEMICO.PERSONANATURALGENERAL PENG,"
					+"ACADEMICO.MATRICULAACADEMICA MAAC,ACADEMICO.CATEGORIA CATE,ACADEMICO.SITUACIONESTUDIANTE SITE,ACADEMICO.FRANJA FRAN"
					+"WHERE ESTP.FRAN_ID=FRAN.FRAN_ID"
					+"AND ESTP.CATE_ID=CATE.CATE_ID"
					+"AND ESTP.SITE_ID=SITE.SITE_ID"
					+"AND MAAC.ESTP_ID(+)=ESTP.ESTP_ID"
					+"AND ESTP.SITE_ID IN(5,11)"
					+"AND ESTP.PEGE_ID=PEGE.PEGE_ID"
					+"AND ESTP.UNPR_ID=UNPR.UNPR_ID"
					+"AND UNPR.PROG_ID=PROG.PROG_ID"
					+"AND LIQU.LIQU_ESTADO='PENDIENTE'"
					+"AND MAAC.MAAC_ESTADO='ACTIVA'"
					+"AND LIQU.LIQU_TIPOLIQUIDACION='NORMAL'"
					+"AND PROG.TPPA_ID=1 AND LIQU.ESTP_ID(+)=ESTP.ESTP_ID"
					+"AND LIQU.PEUN_ID=452"
					+"AND MAAC.PEUN_ID(+)=452"
					+"AND LIQU.LIQU_ESTADO NOT IN 'ANULADO'"
					+"AND PENG.PEGE_ID="+P_ID+""
					+"UNION"
					+"SELECT LIQU.LIQU_ID,PEGE.PEGE_DOCUMENTOIDENTIDAD AS DOCUMENTO,PENG.PENG_PRIMERAPELLIDO||' '||PENG.PENG_SEGUNDOAPELLIDO||' '||PENG.PENG_PRIMERNOMBRE||' '||PENG.PENG_SEGUNDONOMBRE AS NOMBRE,"
					+"PROG.PROG_CODIGOPROGRAMA AS COD_PROG,PROG.PROG_NOMBRE AS PROGRAMA,FRAN.FRAN_DESCRIPCION AS FRANJA,CATE.CATE_DESCRIPCION AS CATEGORIA,SITE.SITE_DESCRIPCION AS SITUACION,"
					+"ESTP.ESTP_ID,LIQU.LIQU_TOTALLIQUIDADO AS TOTAPAGAR,LIQU.LIQU_TOTALDESCUENTO AS DESCUENTO, LIQU.LIQU_VALORPAGADO AS V_PAGADO,LIQU.LIQU_ESTADO,LIQU.LIQU_TIPOLIQUIDACION AS TIPO_LIQU,"
					+"MAAC.MAAC_ESTADO,LIQU.PEUN_ID,MAAC.PEUN_ID AS PEUN_MATRICULA,ESTP.ESTP_PERIODOACADEMICO AS SEMESTRE"
					+"FROM ACADEMICO.LIQUIDACION LIQU,ACADEMICO.ESTUDIANTEPENSUM ESTP,ACADEMICO.PROGRAMA PROG,ACADEMICO.UNIDADPROGRAMA UNPR,ACADEMICO.PERSONAGENERAL PEGE,ACADEMICO.PERSONANATURALGENERAL PENG,"
					+"ACADEMICO.MATRICULAACADEMICA MAAC,ACADEMICO.CATEGORIA CATE,ACADEMICO.SITUACIONESTUDIANTE SITE,ACADEMICO.FRANJA FRAN"
					+"WHERE ESTP.FRAN_ID=FRAN.FRAN_ID"
					+"AND ESTP.CATE_ID=CATE.CATE_ID"
					+"AND ESTP.SITE_ID=SITE.SITE_ID"
					+"AND MAAC.ESTP_ID(+)=ESTP.ESTP_ID"
					+"AND ESTP.SITE_ID IN(5,11)"
					+"AND ESTP.PEGE_ID=PEGE.PEGE_ID"
					+"AND ESTP.UNPR_ID=UNPR.UNPR_ID"
					+"AND UNPR.PROG_ID=PROG.PROG_ID"
					+"AND LIQU.LIQU_ESTADO='PENDIENTE'"
					+"AND LIQU.LIQU_VALORPAGADO>=0"
					+"AND MAAC.MAAC_ESTADO IS NULL"
					+"AND LIQU.LIQU_TIPOLIQUIDACION='NORMAL'"
					+"AND PROG.TPPA_ID=1"
					+"AND LIQU.ESTP_ID(+)=ESTP.ESTP_ID"
					+"AND LIQU.PEUN_ID=452"
					+"AND MAAC.PEUN_ID(+)=452"
					+"AND LIQU.LIQU_ESTADO NOT IN 'ANULADO'"
					+"AND PENG.PEGE_ID="+P_ID+""
					+"UNION"
					+"SELECT LIQU.LIQU_ID,PEGE.PEGE_DOCUMENTOIDENTIDAD AS DOCUMENTO,PENG.PENG_PRIMERAPELLIDO||' '||PENG.PENG_SEGUNDOAPELLIDO||' '||PENG.PENG_PRIMERNOMBRE||' '||PENG.PENG_SEGUNDONOMBRE AS NOMBRE,"
					+"PROG.PROG_CODIGOPROGRAMA AS COD_PROG,PROG.PROG_NOMBRE AS PROGRAMA,FRAN.FRAN_DESCRIPCION AS FRANJA,CATE.CATE_DESCRIPCION AS CATEGORIA,SITE.SITE_DESCRIPCION AS SITUACION,"
					+"ESTP.ESTP_ID,LIQU.LIQU_TOTALLIQUIDADO AS TOTAPAGAR,LIQU.LIQU_TOTALDESCUENTO AS DESCUENTO, LIQU.LIQU_VALORPAGADO AS V_PAGADO,LIQU.LIQU_ESTADO,LIQU.LIQU_TIPOLIQUIDACION AS TIPO_LIQU,"
					+"MAAC.MAAC_ESTADO,LIQU.PEUN_ID,MAAC.PEUN_ID AS PEUN_MATRICULA,ESTP.ESTP_PERIODOACADEMICO AS SEMESTRE"
					+"FROM ACADEMICO.LIQUIDACION LIQU,ACADEMICO.ESTUDIANTEPENSUM ESTP,ACADEMICO.PROGRAMA PROG,ACADEMICO.UNIDADPROGRAMA UNPR,ACADEMICO.PERSONAGENERAL PEGE,ACADEMICO.PERSONANATURALGENERAL PENG,"
					+"ACADEMICO.MATRICULAACADEMICA MAAC,ACADEMICO.CATEGORIA CATE,ACADEMICO.SITUACIONESTUDIANTE SITE,ACADEMICO.FRANJA FRAN"
					+"WHERE ESTP.FRAN_ID=FRAN.FRAN_ID"
					+"AND ESTP.CATE_ID=CATE.CATE_ID"
					+"AND ESTP.SITE_ID=SITE.SITE_ID"
					+"AND MAAC.ESTP_ID(+)=ESTP.ESTP_ID"
					+"AND ESTP.SITE_ID IN(5,11)"
					+"AND ESTP.ESTP_PERIODOACADEMICO NOT IN(7)"
					+"AND PROG.MODA_ID=2"
					+"AND ESTP.PEGE_ID=PEGE.PEGE_ID"
					+"AND CATE.CATE_ID NOT IN 6"
					+"AND ESTP.UNPR_ID=UNPR.UNPR_ID"
					+"AND UNPR.PROG_ID=PROG.PROG_ID"
					+"AND LIQU.LIQU_ESTADO='PENDIENTE'"
					+"AND LIQU.LIQU_VALORPAGADO IS NULL"
					+"AND MAAC.MAAC_ESTADO IS NULL"
					+"AND LIQU.LIQU_TIPOLIQUIDACION='NORMAL'"
					+"AND PROG.TPPA_ID=1"
					+"AND LIQU.ESTP_ID(+)=ESTP.ESTP_ID"
					+"AND LIQU.PEUN_ID=452"
					+"AND MAAC.PEUN_ID(+)=452"
					+"AND LIQU.LIQU_ESTADO NOT IN 'ANULADO'"
					+"AND PENG.PEGE_ID="+P_ID+""
					+"UNION"
					+"SELECT LIQU.LIQU_ID,PEGE.PEGE_DOCUMENTOIDENTIDAD AS DOCUMENTO,PENG.PENG_PRIMERAPELLIDO||' '||PENG.PENG_SEGUNDOAPELLIDO||' '||PENG.PENG_PRIMERNOMBRE||' '||PENG.PENG_SEGUNDONOMBRE AS NOMBRE,"
					+"PROG.PROG_CODIGOPROGRAMA AS COD_PROG,PROG.PROG_NOMBRE AS PROGRAMA,FRAN.FRAN_DESCRIPCION AS FRANJA,CATE.CATE_DESCRIPCION AS CATEGORIA,SITE.SITE_DESCRIPCION AS SITUACION,"
					+"ESTP.ESTP_ID,LIQU.LIQU_TOTALLIQUIDADO AS TOTAPAGAR,LIQU.LIQU_TOTALDESCUENTO AS DESCUENTO, LIQU.LIQU_VALORPAGADO AS V_PAGADO,LIQU.LIQU_ESTADO,LIQU.LIQU_TIPOLIQUIDACION AS TIPO_LIQU,"
					+"MAAC.MAAC_ESTADO,LIQU.PEUN_ID,MAAC.PEUN_ID AS PEUN_MATRICULA,ESTP.ESTP_PERIODOACADEMICO AS SEMESTRE"
					+"FROM ACADEMICO.LIQUIDACION LIQU,ACADEMICO.ESTUDIANTEPENSUM ESTP,ACADEMICO.PROGRAMA PROG,ACADEMICO.UNIDADPROGRAMA UNPR,ACADEMICO.PERSONAGENERAL PEGE,ACADEMICO.PERSONANATURALGENERAL PENG,"
					+"ACADEMICO.MATRICULAACADEMICA MAAC,ACADEMICO.CATEGORIA CATE,ACADEMICO.SITUACIONESTUDIANTE SITE,ACADEMICO.FRANJA FRAN"
					+"WHERE ESTP.FRAN_ID=FRAN.FRAN_ID"
					+"AND ESTP.CATE_ID=CATE.CATE_ID"
					+"AND ESTP.SITE_ID=SITE.SITE_ID"
					+"AND MAAC.ESTP_ID(+)=ESTP.ESTP_ID"
					+"AND ESTP.SITE_ID IN(5,11)"
					+"AND ESTP.ESTP_PERIODOACADEMICO NOT IN(10,11,12)"
					+"AND PROG.MODA_ID=3"
					+"AND ESTP.PEGE_ID=PEGE.PEGE_ID"
					+"AND ESTP.UNPR_ID=UNPR.UNPR_ID"
					+"AND CATE.CATE_ID NOT IN 6"
					+"AND UNPR.PROG_ID=PROG.PROG_ID"
					+"AND LIQU.LIQU_ESTADO='PENDIENTE'"
					+"AND LIQU.LIQU_VALORPAGADO IS NULL" 
					+"AND MAAC.MAAC_ESTADO IS NULL"
					+"AND LIQU.LIQU_TIPOLIQUIDACION='NORMAL'"
					+"AND PROG.TPPA_ID=1"
					+"AND LIQU.ESTP_ID(+)=ESTP.ESTP_ID"
					+"AND LIQU.PEUN_ID=452"
					+"AND MAAC.PEUN_ID(+)=452"
					+"AND LIQU.LIQU_ESTADO NOT IN 'ANULADO'"
					+"AND PENG.PEGE_ID="+P_ID+""
					+"UNION"
					+"SELECT LIQU.LIQU_ID,PEGE.PEGE_DOCUMENTOIDENTIDAD AS DOCUMENTO,PENG.PENG_PRIMERAPELLIDO||' '||PENG.PENG_SEGUNDOAPELLIDO||' '||PENG.PENG_PRIMERNOMBRE||' '||PENG.PENG_SEGUNDONOMBRE AS NOMBRE,"
					+"PROG.PROG_CODIGOPROGRAMA AS COD_PROG,PROG.PROG_NOMBRE AS PROGRAMA,FRAN.FRAN_DESCRIPCION AS FRANJA,CATE.CATE_DESCRIPCION AS CATEGORIA,SITE.SITE_DESCRIPCION AS SITUACION,"
					+"ESTP.ESTP_ID,LIQU.LIQU_TOTALLIQUIDADO AS TOTAPAGAR,LIQU.LIQU_TOTALDESCUENTO AS DESCUENTO, LIQU.LIQU_VALORPAGADO AS V_PAGADO,LIQU.LIQU_ESTADO,LIQU.LIQU_TIPOLIQUIDACION AS TIPO_LIQU,"
					+"MAAC.MAAC_ESTADO,LIQU.PEUN_ID,MAAC.PEUN_ID AS PEUN_MATRICULA,ESTP.ESTP_PERIODOACADEMICO AS SEMESTRE"
					+"FROM ACADEMICO.LIQUIDACION LIQU,ACADEMICO.ESTUDIANTEPENSUM ESTP,ACADEMICO.PROGRAMA PROG,ACADEMICO.UNIDADPROGRAMA UNPR,ACADEMICO.PERSONAGENERAL PEGE,ACADEMICO.PERSONANATURALGENERAL PENG,"
					+"ACADEMICO.MATRICULAACADEMICA MAAC,ACADEMICO.CATEGORIA CATE,ACADEMICO.SITUACIONESTUDIANTE SITE,ACADEMICO.FRANJA FRAN"
					+"WHERE ESTP.FRAN_ID=FRAN.FRAN_ID"
					+"AND ESTP.CATE_ID=CATE.CATE_ID"
					+"AND ESTP.SITE_ID=SITE.SITE_ID"
					+"AND MAAC.ESTP_ID(+)=ESTP.ESTP_ID"
					+"AND ESTP.SITE_ID IN(5,11)"
					+"AND ESTP.ESTP_PERIODOACADEMICO NOT IN(4)"
					+"AND PROG.MODA_ID=19"
					+"AND ESTP.PEGE_ID=PEGE.PEGE_ID"
					+"AND ESTP.UNPR_ID=UNPR.UNPR_ID"
					+"AND CATE.CATE_ID NOT IN 6"
					+"AND UNPR.PROG_ID=PROG.PROG_ID"
					+"AND LIQU.LIQU_ESTADO='PENDIENTE'"
					+"AND LIQU.LIQU_VALORPAGADO IS NULL"
					+"AND MAAC.MAAC_ESTADO IS NULL"
					+"AND LIQU.LIQU_TIPOLIQUIDACION='NORMAL'"
					+"AND PROG.TPPA_ID=1"
					+"AND LIQU.ESTP_ID(+)=ESTP.ESTP_ID"
					+"AND LIQU.PEUN_ID=452"
					+"AND MAAC.PEUN_ID(+)=452"
					+"AND LIQU.LIQU_ESTADO NOT IN 'ANULADO'"
					+"AND PENG.PEGE_ID="+P_ID+""
					+"UNION"
					+"SELECT LIQU.LIQU_ID,PEGE.PEGE_DOCUMENTOIDENTIDAD AS DOCUMENTO,PENG.PENG_PRIMERAPELLIDO||' '||PENG.PENG_SEGUNDOAPELLIDO||' '||PENG.PENG_PRIMERNOMBRE||' '||PENG.PENG_SEGUNDONOMBRE AS NOMBRE,"
					+"PROG.PROG_CODIGOPROGRAMA AS COD_PROG,PROG.PROG_NOMBRE AS PROGRAMA,FRAN.FRAN_DESCRIPCION AS FRANJA,CATE.CATE_DESCRIPCION AS CATEGORIA,SITE.SITE_DESCRIPCION AS SITUACION,"
					+"ESTP.ESTP_ID,LIQU.LIQU_TOTALLIQUIDADO AS TOTAPAGAR,LIQU.LIQU_TOTALDESCUENTO AS DESCUENTO, LIQU.LIQU_VALORPAGADO AS V_PAGADO,LIQU.LIQU_ESTADO,LIQU.LIQU_TIPOLIQUIDACION AS TIPO_LIQU,"
					+"MAAC.MAAC_ESTADO,LIQU.PEUN_ID,MAAC.PEUN_ID AS PEUN_MATRICULA,ESTP.ESTP_PERIODOACADEMICO AS SEMESTRE"
					+"FROM ACADEMICO.LIQUIDACION LIQU,ACADEMICO.ESTUDIANTEPENSUM ESTP,ACADEMICO.PROGRAMA PROG,ACADEMICO.UNIDADPROGRAMA UNPR,ACADEMICO.PERSONAGENERAL PEGE,ACADEMICO.PERSONANATURALGENERAL PENG,"
					+"ACADEMICO.MATRICULAACADEMICA MAAC,ACADEMICO.CATEGORIA CATE,ACADEMICO.SITUACIONESTUDIANTE SITE,ACADEMICO.FRANJA FRAN"
					+"WHERE ESTP.FRAN_ID=FRAN.FRAN_ID"
					+"AND ESTP.CATE_ID=CATE.CATE_ID"
					+"AND ESTP.SITE_ID=SITE.SITE_ID"
					+"AND MAAC.ESTP_ID(+)=ESTP.ESTP_ID"
					+"AND ESTP.SITE_ID IN(5,11)"
					+"AND ESTP.ESTP_PERIODOACADEMICO NOT IN(4)"
					+"AND PROG.MODA_ID=1"
					+"AND ESTP.PEGE_ID=PEGE.PEGE_ID"
					+"AND CATE.CATE_ID NOT IN 6"
					+"AND ESTP.UNPR_ID=UNPR.UNPR_ID"
					+"AND UNPR.PROG_ID=PROG.PROG_ID"
					+"AND LIQU.LIQU_ESTADO='PENDIENTE'"
					+"AND LIQU.LIQU_VALORPAGADO IS NULL"
					+"AND MAAC.MAAC_ESTADO IS NULL"
					+"AND LIQU.LIQU_TIPOLIQUIDACION='NORMAL'"
					+"AND PROG.TPPA_ID=1"
					+"AND LIQU.ESTP_ID(+)=ESTP.ESTP_ID"
					+"AND LIQU.PEUN_ID=452"
					+"AND MAAC.PEUN_ID(+)=452"
					+"AND LIQU.LIQU_ESTADO NOT IN 'ANULADO'"
					+"AND PENG.PEGE_ID="+P_ID+""
					+"ORDER BY LIQU_ESTADO,MAAC_ESTADO,PROGRAMA,FRANJA,NOMBRE");
			ResultSet rs=conn.query(sql);
			if(rs.next()){
			   Liqui.setLIQU_ID(rs.getString("LIQU_ID"));
			   Liqui.setDOCUMENTO(rs.getString("DOCUMENTO"));
			   Liqui.setNOMBRE(rs.getString("NOMBRE"));
			   Liqui.setCOD_PROG(rs.getString("COD_PROG"));
			   Liqui.setPROGRAMA(rs.getString("ROGRAMA"));
			   Liqui.setFRANJA(rs.getString("FRANJA"));
			   Liqui.setCATEGORIA(rs.getString("CATEGORIA"));
			   Liqui.setSITUACION(rs.getString("SITUACION"));
			   Liqui.setESTP_ID(rs.getString("DSTP_ID"));
			   Liqui.setTOTAPAGAR(rs.getString("TOTAPAGAR"));
			   Liqui.setDESCUENTO(rs.getString("DESCUENTO"));
			   Liqui.setV_PAGADO(rs.getString("V_PAGADO"));
			   Liqui.setLIQU_ESTADO(rs.getString("LIQU_ESTADO"));
			   Liqui.setTIPO_LIQU(rs.getString("TIPO_LIQU"));
			   Liqui.setMAAC_ESTADO(rs.getString("MAAC_ESTADO"));
			   Liqui.setPEUN_ID(rs.getString("PEUN_ID"));
			   Liqui.setPEUN_MATRICULA(rs.getString("PEUN_MATRICULA"));
			   Liqui.setSEMESTRE(rs.getString("SEMESTRE"));
	
			   }
			
			return Liqui;
		 } catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
			  conn.disconnect();
			  return null;
		}
		
	}
	
		
}
